wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715369340.0
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 55
      3:
      - 19
      - 23
      - 61
      4: 3.11.7
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
num_episodes:
  desc: null
  value: 100000
batch_size:
  desc: null
  value: 8
